use serde::Serialize;

#[derive(Debug, Clone, Copy, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum PublicEndpointKind {
    Collection,
    Singleton,
    CallOnly,
}

#[derive(Debug, Clone, Copy, Serialize, PartialEq, Eq)]
pub struct PublicEndpointSpec {
    pub key: &'static str,
    pub path: &'static str,
    pub lang: bool,
    pub auth: bool,
    pub active: bool,
    pub kind: PublicEndpointKind,
    pub path_params: &'static [&'static str],
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ExcludedEndpointSpec {
    pub key: &'static str,
    pub path: &'static str,
    pub auth: bool,
    pub active: bool,
}

pub const PUBLIC_ENDPOINTS: &[PublicEndpointSpec] = &[
    PublicEndpointSpec {
        key: "account_home",
        path: "/v2/account/home",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Singleton,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "account_homestead",
        path: "/v2/account/homestead",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Singleton,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "account_mounts",
        path: "/v2/account/mounts",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Singleton,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "achievements",
        path: "/v2/achievements",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "achievements_categories",
        path: "/v2/achievements/categories",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "achievements_groups",
        path: "/v2/achievements/groups",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "backstory_answers",
        path: "/v2/backstory/answers",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "backstory_questions",
        path: "/v2/backstory/questions",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "build",
        path: "/v2/build",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Singleton,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "colors",
        path: "/v2/colors",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "commerce_exchange",
        path: "/v2/commerce/exchange",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::CallOnly,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "commerce_listings",
        path: "/v2/commerce/listings",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "commerce_prices",
        path: "/v2/commerce/prices",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "continents",
        path: "/v2/continents",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "currencies",
        path: "/v2/currencies",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "dailycrafting",
        path: "/v2/dailycrafting",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "dungeons",
        path: "/v2/dungeons",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "emblem",
        path: "/v2/emblem",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Singleton,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "emotes",
        path: "/v2/emotes",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "files",
        path: "/v2/files",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Singleton,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "finishers",
        path: "/v2/finishers",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "gliders",
        path: "/v2/gliders",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "guild_permissions",
        path: "/v2/guild/permissions",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "guild_search",
        path: "/v2/guild/search",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::CallOnly,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "guild_upgrades",
        path: "/v2/guild/upgrades",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "home",
        path: "/v2/home",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Singleton,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "home_cats",
        path: "/v2/home/cats",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "home_nodes",
        path: "/v2/home/nodes",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "homestead",
        path: "/v2/homestead",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Singleton,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "homestead_decorations",
        path: "/v2/homestead/decorations",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "homestead_decorations_categories",
        path: "/v2/homestead/decorations/categories",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "homestead_decorations_category_by_id",
        path: "/v2/homestead/decorations/categories/:id",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::CallOnly,
        path_params: &["id"],
    },
    PublicEndpointSpec {
        key: "homestead_glyphs",
        path: "/v2/homestead/glyphs",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "items",
        path: "/v2/items",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "itemstats",
        path: "/v2/itemstats",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "jadebots",
        path: "/v2/jadebots",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "legendaryarmory",
        path: "/v2/legendaryarmory",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Singleton,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "legends",
        path: "/v2/legends",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "logos",
        path: "/v2/logos",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Singleton,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "mailcarriers",
        path: "/v2/mailcarriers",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "mapchests",
        path: "/v2/mapchests",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "maps",
        path: "/v2/maps",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "masteries",
        path: "/v2/masteries",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "materials",
        path: "/v2/materials",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "minis",
        path: "/v2/minis",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "mounts",
        path: "/v2/mounts",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Singleton,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "mounts_skins",
        path: "/v2/mounts/skins",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "mounts_types",
        path: "/v2/mounts/types",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "novelties",
        path: "/v2/novelties",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "outfits",
        path: "/v2/outfits",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "pets",
        path: "/v2/pets",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "professions",
        path: "/v2/professions",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "pvp",
        path: "/v2/pvp",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Singleton,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "pvp_amulets",
        path: "/v2/pvp/amulets",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "pvp_heroes",
        path: "/v2/pvp/heroes",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "pvp_ranks",
        path: "/v2/pvp/ranks",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "pvp_seasons",
        path: "/v2/pvp/seasons",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "pvp_season_leaderboards",
        path: "/v2/pvp/seasons/:id/leaderboards",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::CallOnly,
        path_params: &["id"],
    },
    PublicEndpointSpec {
        key: "pvp_season_leaderboard_entries",
        path: "/v2/pvp/seasons/:id/leaderboards/:board/:region",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::CallOnly,
        path_params: &["id", "board", "region"],
    },
    PublicEndpointSpec {
        key: "quaggans",
        path: "/v2/quaggans",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "quests",
        path: "/v2/quests",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "races",
        path: "/v2/races",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "raids",
        path: "/v2/raids",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "recipes",
        path: "/v2/recipes",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "recipes_search",
        path: "/v2/recipes/search",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::CallOnly,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "skiffs",
        path: "/v2/skiffs",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "skills",
        path: "/v2/skills",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "skins",
        path: "/v2/skins",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "specializations",
        path: "/v2/specializations",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "stories",
        path: "/v2/stories",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "stories_seasons",
        path: "/v2/stories/seasons",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "titles",
        path: "/v2/titles",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "wizardsvault_listings",
        path: "/v2/wizardsvault/listings",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "wizardsvault_objectives",
        path: "/v2/wizardsvault/objectives",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "worldbosses",
        path: "/v2/worldbosses",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "worlds",
        path: "/v2/worlds",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "wvw_abilities",
        path: "/v2/wvw/abilities",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "wvw_guilds",
        path: "/v2/wvw/guilds",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::CallOnly,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "wvw_guilds_by_region",
        path: "/v2/wvw/guilds/:region",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::CallOnly,
        path_params: &["region"],
    },
    PublicEndpointSpec {
        key: "wvw_matches",
        path: "/v2/wvw/matches",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "wvw_matches_overview",
        path: "/v2/wvw/matches/overview",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "wvw_matches_scores",
        path: "/v2/wvw/matches/scores",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "wvw_matches_stats",
        path: "/v2/wvw/matches/stats",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "wvw_match_stat_guilds",
        path: "/v2/wvw/matches/stats/:id/guilds/:guild_id",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::CallOnly,
        path_params: &["id", "guild_id"],
    },
    PublicEndpointSpec {
        key: "wvw_match_team_top_kdr",
        path: "/v2/wvw/matches/stats/:id/teams/:team/top/kdr",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::CallOnly,
        path_params: &["id", "team"],
    },
    PublicEndpointSpec {
        key: "wvw_match_team_top_kills",
        path: "/v2/wvw/matches/stats/:id/teams/:team/top/kills",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::CallOnly,
        path_params: &["id", "team"],
    },
    PublicEndpointSpec {
        key: "wvw_objectives",
        path: "/v2/wvw/objectives",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "wvw_ranks",
        path: "/v2/wvw/ranks",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "wvw_timers",
        path: "/v2/wvw/timers",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "wvw_timers_lockout",
        path: "/v2/wvw/timers/lockout",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Singleton,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "wvw_timers_team_assignment",
        path: "/v2/wvw/timers/teamAssignment",
        lang: false,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Singleton,
        path_params: &[],
    },
    PublicEndpointSpec {
        key: "wvw_upgrades",
        path: "/v2/wvw/upgrades",
        lang: true,
        auth: false,
        active: true,
        kind: PublicEndpointKind::Collection,
        path_params: &[],
    },
];

const EXCLUDED_ENDPOINTS: &[ExcludedEndpointSpec] = &[
    ExcludedEndpointSpec {
        key: "account",
        path: "/v2/account",
        auth: true,
        active: true,
    },
    ExcludedEndpointSpec {
        key: "characters",
        path: "/v2/characters",
        auth: true,
        active: true,
    },
    ExcludedEndpointSpec {
        key: "tokeninfo",
        path: "/v2/tokeninfo",
        auth: true,
        active: true,
    },
    ExcludedEndpointSpec {
        key: "achievements_daily",
        path: "/v2/achievements/daily",
        auth: false,
        active: false,
    },
    ExcludedEndpointSpec {
        key: "achievements_daily_tomorrow",
        path: "/v2/achievements/daily/tomorrow",
        auth: false,
        active: false,
    },
    ExcludedEndpointSpec {
        key: "adventures",
        path: "/v2/adventures",
        auth: false,
        active: false,
    },
    ExcludedEndpointSpec {
        key: "events",
        path: "/v2/events",
        auth: false,
        active: false,
    },
    ExcludedEndpointSpec {
        key: "events_state",
        path: "/v2/events-state",
        auth: false,
        active: false,
    },
    ExcludedEndpointSpec {
        key: "gemstore_catalog",
        path: "/v2/gemstore/catalog",
        auth: false,
        active: false,
    },
    ExcludedEndpointSpec {
        key: "pvp_rewardtracks",
        path: "/v2/pvp/rewardtracks",
        auth: false,
        active: false,
    },
    ExcludedEndpointSpec {
        key: "pvp_runes",
        path: "/v2/pvp/runes",
        auth: false,
        active: false,
    },
    ExcludedEndpointSpec {
        key: "pvp_sigils",
        path: "/v2/pvp/sigils",
        auth: false,
        active: false,
    },
    ExcludedEndpointSpec {
        key: "vendors",
        path: "/v2/vendors",
        auth: false,
        active: false,
    },
    ExcludedEndpointSpec {
        key: "wvw_rewardtracks",
        path: "/v2/wvw/rewardtracks",
        auth: false,
        active: false,
    },
];

pub fn public_endpoints() -> &'static [PublicEndpointSpec] {
    PUBLIC_ENDPOINTS
}

pub fn public_endpoint(key: &str) -> Option<&'static PublicEndpointSpec> {
    PUBLIC_ENDPOINTS.iter().find(|endpoint| endpoint.key == key)
}

pub fn excluded_endpoint(key: &str) -> Option<&'static ExcludedEndpointSpec> {
    EXCLUDED_ENDPOINTS
        .iter()
        .find(|endpoint| endpoint.key == key)
}
